use bigint::{U256, U512};
use field::{DefaultBackend, FpConfig};
use field_core::{Fp, WideEuclideanBackend, WideFieldConfig};

pub use field_core::{FpBackend, WideInt};

pub use elliptic_curve::ShortWeierstrassCurve;

// secp256k1's base field modulus, p = 2^256 - 2^32 - 977. Chosen (like
// Goldilocks' 2^64 - 2^32 + 1) so that 2^256 collapses to a small constant
// mod p, which FieldConfig::mul below exploits for a division-free
// reduction -- see secp256k1_reduce512's doc comment.
const SECP256K1_P: U256 = U256::from_limbs([
    0xffff_fffe_ffff_fc2f,
    0xffff_ffff_ffff_ffff,
    0xffff_ffff_ffff_ffff,
    0xffff_ffff_ffff_ffff,
]);

// C = 2^32 + 977, i.e. p's "epsilon": 2^256 == C (mod p). The base field's
// analogue of Goldilocks' EPSILON = 2^32 - 1 (2^64 == 2^32 - 1 mod p) --
// same idea, just a different small constant for a different prime shape.
const SECP256K1_C: U256 = U256::from_u64(0x1_0000_03D1);

// x = x_hi*2^256 + x_lo == x_hi*C + x_lo (mod p), the same identity
// Goldilocks' reduce128 exploits at 64 bits. Unlike Goldilocks (where x_hi
// is at most 64 bits and a single fold finishes the job), a 512-bit
// product's x_hi can itself be up to 256 bits wide, so one fold only
// shrinks the value to roughly 257 bits rather than fitting it in a single
// word. Folding repeatedly -- each time replacing the bits above 255 with
// their product against the 33-bit C -- converges fast regardless: the
// excess bit-width shrinks by roughly (256 - 33) bits per iteration,
// reaching <=256 bits within a handful of folds for any input under 2^512.
// A final comparison loop against MODULUS then canonicalizes the (already
// tiny) excess above p.
fn secp256k1_reduce512(x: U512) -> U256 {
    let mut acc = x;

    while (acc >> 256) != U512::ZERO {
        let hi: U256 = (acc >> 256).resize();
        let lo: U256 = acc.resize();

        acc = (hi * SECP256K1_C) + lo.resize();
    }

    let mut result: U256 = acc.resize();
    while result >= SECP256K1_P {
        result -= SECP256K1_P;
    }

    result
}

// The base field's WideFieldConfig: only `mul` is hand-written (the fast
// fold-based reduction above). add/sub/neg/one and the default square
// (mul(a,a)) all come for free from WideEuclideanBackend below via U256's
// WideInt impl (bigint) -- including a correctly-wide add/sub even though
// MODULUS sits close to U256's full bit width, which a naive same-width add
// would silently overflow (see WideEuclideanBackend's doc comment in
// field-core). That's the whole payoff of routing through WideFieldConfig
// here instead of hand-rolling every FpBackend method the way the scalar
// field's DefaultBackend<ScalarConfig> below has to.
pub struct FieldConfig;

impl WideFieldConfig for FieldConfig {
    type Repr = U256;

    const MODULUS: U256 = SECP256K1_P;

    fn mul(a: U256, b: U256) -> U256 {
        secp256k1_reduce512(a * b)
    }
}

pub type FieldBackend = WideEuclideanBackend<FieldConfig>;

// secp256k1's group order n, i.e. the size of the prime-order subgroup
// generated by G. Scalars for scalar multiplication live in this field, not
// the base field above. Unlike p, n has no power-of-two-minus-small-constant
// shape to exploit, so it keeps the generic division-based reduction.
pub struct ScalarConfig;

impl FpConfig for ScalarConfig {
    const MODULUS: U256 = U256::from_limbs([
        0xbfd2_5e8c_d036_4141,
        0xbaae_dce6_af48_a03b,
        0xffff_ffff_ffff_fffe,
        0xffff_ffff_ffff_ffff,
    ]);
}

pub type Secp256k1Field = Fp<FieldBackend>;
pub type Secp256k1Scalar = Fp<DefaultBackend<ScalarConfig>>;

pub struct Secp256k1;

// y^2 = x^3 + 7: secp256k1 is a=0, b=7 short Weierstrass curve.
impl ShortWeierstrassCurve for Secp256k1 {
    type Field = Secp256k1Field;
    type Scalar = Secp256k1Scalar;

    const A: Self::Field = Secp256k1Field::new(U256::ZERO);
    const B: Self::Field = Secp256k1Field::new(U256::from_u64(7));
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    #[test]
    fn field_modulus_matches_known_value() {
        // p = 2^256 - 2^32 - 977, so p + 2^32 + 977 wraps to 0 mod 2^256 --
        // Add wraps silently (see Uint::add in bigint), so this is a direct
        // check of the defining equation rather than a hardcoded value.
        let sum = SECP256K1_P + (U256::ONE << 32) + U256::from_u64(977);
        assert_eq!(sum, U256::ZERO);
    }

    #[test]
    fn scalar_modulus_matches_known_value() {
        // n has no closed-form definition like p above, so cross-check the
        // from_limbs (64-bit) constant against an independent decomposition
        // built from the commonly published 32-bit words:
        // FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE BAAEDCE6 AF48A03B BFD25E8C D0364141
        let n = (U256::from_u64(0xFFFFFFFF) << 224)
            + (U256::from_u64(0xFFFFFFFF) << 192)
            + (U256::from_u64(0xFFFFFFFF) << 160)
            + (U256::from_u64(0xFFFFFFFE) << 128)
            + (U256::from_u64(0xBAAEDCE6) << 96)
            + (U256::from_u64(0xAF48A03B) << 64)
            + (U256::from_u64(0xBFD25E8C) << 32)
            + U256::from_u64(0xD0364141);

        assert_eq!(ScalarConfig::MODULUS, n);
    }

    #[test]
    fn scalar_modulus_is_smaller_than_field_modulus() {
        // n < p for secp256k1 (the curve's order is close to, but smaller
        // than, the field size -- Hasse's theorem).
        assert!(ScalarConfig::MODULUS < SECP256K1_P);
    }

    #[test]
    fn curve_coefficients_are_a_zero_b_seven() {
        // Fp doesn't implement Debug, so assert! + == (not assert_eq!) --
        // same convention as elliptic-curve's own point-equality tests.
        assert!(Secp256k1::A == Secp256k1Field::new(U256::ZERO));
        assert!(Secp256k1::B == Secp256k1Field::new(U256::from_u64(7)));
    }

    // Builds a field element from 4 arbitrary u64 limbs, reduced mod p --
    // covers the field's full magnitude range (not just small values),
    // which matters here since the thing under test is a reduction routine.
    fn fe(limbs: [u64; 4]) -> Secp256k1Field {
        let raw = U256::from_limbs(limbs);
        let reduced = (raw.resize::<8>() % SECP256K1_P.resize::<8>()).resize();

        Secp256k1Field::new(reduced)
    }

    #[test]
    fn mul_max_values() {
        let max = Secp256k1Field::new(SECP256K1_P - U256::ONE);
        let expected: U256 = ((max.value * max.value) % SECP256K1_P.resize::<8>()).resize();

        assert!((max * max).value == expected);
    }

    proptest! {
        // Cross-checks secp256k1_reduce512's folding reduction (used by
        // FieldBackend::mul/square) against a plain U512 % MODULUS division
        // -- the same reference computation field::DefaultBackend::mul
        // performs -- across the field's full value range, not just the one
        // hand-picked example above.
        #[test]
        fn mul_matches_naive_reduction(
            a_limbs in any::<[u64; 4]>(),
            b_limbs in any::<[u64; 4]>(),
        ) {
            let a = fe(a_limbs);
            let b = fe(b_limbs);

            let expected: U256 = (a.value * b.value % SECP256K1_P.resize::<8>()).resize();

            prop_assert!((a * b).value == expected);
        }

        #[test]
        fn square_matches_mul(limbs in any::<[u64; 4]>()) {
            let a = fe(limbs);

            prop_assert!(a.square().value == (a * a).value);
        }

        #[test]
        fn mul_result_is_canonical(a_limbs in any::<[u64; 4]>(), b_limbs in any::<[u64; 4]>()) {
            let a = fe(a_limbs);
            let b = fe(b_limbs);

            prop_assert!((a * b).value < SECP256K1_P);
        }

        #[test]
        fn mul_matches_repeated_addition(limbs in any::<[u64; 4]>(), reps in 0u32..12) {
            // Multiplying by a small integer via repeated field addition is
            // an independent (if slow) reference for the same product, not
            // routed through reduce512 or division at all.
            let a = fe(limbs);
            let mut expected = Secp256k1Field::new(U256::ZERO);
            for _ in 0..reps {
                expected = expected + a;
            }

            let n = Secp256k1Field::new(U256::from_u64(reps as u64));
            prop_assert!((a * n).value == expected.value);
        }

        #[test]
        fn inverse_times_self_is_one(limbs in any::<[u64; 4]>()) {
            let a = fe(limbs);
            prop_assume!(a.value != U256::ZERO);

            prop_assert!((a * a.inverse()).value == U256::ONE);
        }
    }
}
