[package]
name = "babybear"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
field-core = { path = "../field-core" }

[dev-dependencies]
proptest = "1"
criterion = { workspace = true }

[[bench]]
name = "babybear_ops"
harness = false

[[bench]]
name = "babybear_ext_ops"
harness = false
